version: "4.0"
services:
  app:
    build: .
    command: python main.py
    ports:
      - "5000:5000"
    volumes:
      - .:/promo-servicee
    links:
      - db:db
    depends_on:
      - db
  db:
    image: postgres    
    environment:
      POSTGRES_PASSWORD: Mj3nH5
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
   

volumes:
  db-data:
    
